[project]
name = "pythonbook"
version = "0.1.0"
description = "Python book in Arabic"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel",
    "jupyter",
    "jupyter-cache",
    "matplotlib>=3.10.0",
    "pandas",
]
