---
og:title: dates_in_arabic_problem
---

# التاريخ بالعربية {.unnumbered}

كيف نقرأ التواريخ نحو: 7هـ، 84هـ ، 612هـ ، 800هـ ، 1351هـ ، 2025 م؟

لدينا طريقتان:

**الطريقة الأولى**: من اليمين إلى اليسار، حيث نبدأ من خانة الآحاد إلى العشرات إلى المئات إلى الألوف وهلم جرا.

**الطريقة المعاصرة**: من اليسار إلى اليمين وهي الطريقة الشائعة في العربية المعاصرة.

ففي هذا الجدول نقدِّر قولنا: "في سنة" قبل كل جملة حتى تكون في محل جر:

| التاريخ (هـ/م) | الطريقة الأولى | الطريقة المعاصرة |
|--------------|--------------|--------------|
| 7 هـ        | سبع                                  | سبع                                |
| 84 هـ        | أربع وثمانين                                  | أربع وثمانين                                |
| 612 هـ       | اثنين وعشرين وستِّ مئة                         | ستِّ مئة واثني عشر                           |
| 800 هـ       | ثمان مئة                                       | ثمان مئة                                     |
| 1351 هـ      | واحدٍ وخمسين وثلاثِ مئة وألف                   | ألفٍ وثلاثِ مئة وواحدٍ وخمسين               |
| 2025 م       | خمسٍ وعشرين وألفين                             | ألفينِ وخمسةٍ وعشرين                         |

## المسألة

1. اكتب خوارزمية تحول التاريخ من الرقم إلى الكلمات
2. استعمل إحدى الطريقتين
3. أو لكتيهما
4. وإذا راعيت الحالة الإعرابية فذلك أحسن
5. وإن زدت فاجعل الهاء للهجرة والميم للميلاد
6. وإن زدت فاجعل ق.ه قبل الهجرة و ق.م قبل الميلاد


**مثال**:

- المدخلات: 612ه
- المخرجات (بالطريقة الأولى): اثنين وعشرين وستِّ مئة.

واستعمل جمل التوكيد (`assert`) للتحقق من الحل.

```python
def numerical_to_literal(num: str) -> str:
    pass
```