---
og:title: using_problems
---

# مسائل {.unnumbered}

## قراءة توثيق مكتبة (`httpx`)

نرجو منك أولاً قراءة صفحة [البداية السريعة لـ `httpx`](https://www.python-httpx.org/quickstart/) كاملةً بتأني؛ لأنها ستعطيك نظرة عامة على آليات HTTP وكيفية التعبير عنها بلغة بايثون. وذلك لأن HTTP هي لغة التخاطب على شبكة الإنرتنت بين البرمجيات.


## التطبيق على إحدى الواجهات البرمجية

لابد أن تجد في موقع المزوِّد توثيقًا لجميع تفاصيله للاستفادة منه. ابحث عل كلمة **API Documentation** أو **Developers** ونحوهما لتجد التوثيق. وقد تجد عنوانًا مثل: بداية سريعة (Quick Start) أو نحوها للبدء. وعادةً ما يتضمن التوثيق: وصف جميع **نقاط الالتقاء** (Endpoints) التي تحدد العناوين الفرعية التابعة للعنوان الرئيسي للواجهة. الآن دورك. عليك قراءة التوثيق بتمعُّن، والتجول في صفحاته حتى تتعلم كيفية استخدام الواجهة البرمجية لتحقيق مهمة واحدة.

جرب استعمال أحد الواجهات البرمجية التالية:

- [poetrydb](https://poetrydb.org/index.html)
- [newtown](https://newton.vercel.app/)
- [alquran-cloud](https://alquran.cloud/api)
- [Wikipedia](https://pypi.org/project/Wikipedia-API/)
- [nasa](https://api.nasa.gov/)
- [arxiv](https://info.arxiv.org/help/api/user-manual.html)
- [Telegram](https://core.telegram.org/)
- [Discord](https://discord.com/developers/docs/intro)
- [Google AI Studio](https://aistudio.google.com/)

وهنا تجميع لقائمة كبيرة مقسمة اختر منها ما تريد (وقد يكون بعضها لا يعمل): [https://github.com/public-apis/public-apis](https://github.com/public-apis/public-apis).

فإن أردت البحث عن واجهة برمجية لعمل شيء ما، فاكتب الكلمات المفتاحية + "API" في محرك البحث؛ مثلاً: `Google Maps API`.

**ملاحظة**: بعض الواجهات تتطلب التسجيل للحصول على مفتاح API. وبعضها يحتاج إضافة إلى ذلك شحن الحساب برصيد مثل 5 دولارات. وكل ذلك مبين في التوثيق نفسه.
