# الخطأ

ينقسم الخطأ لثلاثة أنواع:

1. **الخطأ النحوي**: وهو الخطأ في مبنى اللغة؛ أي: مخالفة قواعدها وقوانينها. (Syntactic Error)
2. **الخطأ المنطقي**: وهو التعبير بخطوات صحيحة في ذاتها لكنها لا تؤول للنتيجة التي نهدف إليها. (Logical Error)
3. **الخطأ التشغيلي**: ويسمى **الاستثناء** وهو حالة غير مثالية يجب أن يتعامل معها الرنامج. (Runtime Error)
    - يأتي الحديث عنه في [الفصل التالي](a2_exceptions.qmd).

في هذا الفصل، نناقش كل نوع من الأخطاء وكيفية التعامل معها.

## الخطأ النحوي: الخطأ في المبنى

الأخطاء النحوية تتعلق بتركيب اللغة لا أكثر ولا أقل. إليك ثلاثة أمثلة.

### فقدان النقطتين `:`

```{python}
#|error: true
if (x > 5)
    print("x")
```

### علامات اقتباس غير متوازنة

```{python}
#|error: true
print("x
```

### اسم متغير غير صالح

```{python}
#| error: true
my-variable = 10
```

### أخطاء المحاذاة

من الأخطاء النحوية الشائعة في بايثون: أخطاء المحاذاة (Indentation Error).

وذلك أن بايثون تقبل نوعين من المسافات البادئة للسطر؛ إما بحرف المسافة التي بين الكلمات `\s` أو بحرف المسافة بين الأعمدة `\t`. وقد يستعمل بعض الناس هذه وبعضهم ذلك، ثم تأخذ كودًا من هنا وكودًا من هناك، فترى الكود عنك لا يعمل، والسبب هو الخلط بينهما في نفس الكود. وبايثون لا تقبل ذلك. فيجب توحيد النوع. إما هذه أو هذه. لذلك يضبط VS Code ومحررات الأكواد الأخرى تحويل البادئة تلقائيًا إلى مسافة أو العكس.

إليك بعض الأمثلة لما يحصل من أخطاء في المحاذاة:

عدم وجود مسافة بادئة، عندما تكون متوقعة:

```{python}
#| error: true
if True:
print("x")
```

عدم تطابق المحاذاة:

```{python}
#| error: true
if True:
    print("x")
     print('y')
```

### تجويد العبارة

من تجويد العبارة تسمية المتغيرات بما يدل على وظيفتها، مثل:


```{python}
rate = 50
hours_per_day = 6
days = 5
pay = rate * hours_per_day * days
print(pay)
```

وإن كان ليس من الخطأ النحوي كتابتها بطريقة مختلفة وبأسماء غير معبِّرة، إلا أنه فعلٌ غير مستحسن:

```{python}
r, hpd, d = 50, 6, 5
p = r * hpd * d
print(p)
```

وفي هذا نصائح كثيرة، يراجع فيها [دليل أسلوب الكتابة في بايثون](https://peps.python.org/pep-0008/).

## الخطأ المنطقي: الخطأ في المعنى

وهي التي نقصدها حين نقول: **Bug**، ولذلك قيل للبرنامج الذي يساعد في إصلاحها: **Debugger**، وعملية البحث عنها وإصلاحها: **Debugging**.

**الأخطاء المنطقية صامتة**. إذ لا يكتشفها المترجم، وتتسبب في تصرف البرنامج بشكل غير صحيح. الأخطاء المنطقية هي الأصعب في التتبع والإصلاح لأنها ليست واضحة. يمكن أن تكون ناجمة عن:

- افتراضات غير صحيحة
- تطبيق غير صحيح للخوارزمية أو
- تحضير غير صحيح للبيانات

اقرأ المزيد عن [أنواع الأخطاء](https://en.wikipedia.org/wiki/Software_bug#Types) وإليك بعض الأمثلة.

### استعمال الفعل الخاطئ

```{python}
import math

square = math.sqrt(4) # should use math.pow(4, 2) instead
```

### استعمال العامل الخاطئ

```{python}
x = 16
if (x == "16"):
    print('equal')
```

### مستوى محاذاة خاطئ

هنا كانت النية تقتضي أن تكون `print(j)` داخل الحلقة الداخلية:

```{python}
for i in range(2):
    for j in range(3):
        print(i)  
    print(j)
```

### خطأ الحافَّة

يكاد يكون أشهر الأخطاء في البرمجة: خطأ الحافَّة. ويسمى (Off-by-one error).

نشرحه بمثال: النية هنا هي طباعة الأرقام من 5 إلى 0 بما في ذلك 0، ولكن الحلقة تتوقف عند 1.

```{python}
for i in range(5, 0, -1):
    print(i)
```

## كشف الأخطاء المنطقية

لكونها جملاً صحيحة في ذاتها؛ لا يستطيع البرنامج كشف هذه الأخطاء لوحده. بل يجب على من يُدركُ حقيقة المطلوب من البرنامج أن يتكفل بذلك. وهنا تكون الحاجة ماسَّة **لجمل التوكيد**: `assert` وقد رأيناها كثيرًا.

و**التدقيق**؛ إذْ أفضل طريقة لحل الأخطاء المنطقية هي تنفيذ الكود والنظر في الناتج، وتتبع المنطق مرة أخرى إلى الكود سطرًا بسطر. يمكنك استخدام عبارات الطباعة `print` لتصحيح الأخطاء وفهم تدفق البرنامج. وقد يكون الأفضل من ذلك استعمال [**المدقق**](https://code.visualstudio.com/docs/python/debugging) (Debugger).

**مراجعة الأقران**: بحيث يطلع على الكود شخص آخر، فإنه قد يرى منه ما تعذر عليك رؤيته. وقد يتم تنظيمه بين أعضاء الفريق الواحد بأحد برمجيات التعاون مثل: GitHub وGitLab وBitbucket وغيرها. لكن ليس شرطًا أن يكون بطريقة منظَّمة حتى تستفيد منه.

## المصطلحات

| العربية | الإنجليزية |
|------------------|---------------------|
| الخطأ النحوي | Syntactic Error |
| الخطأ المنطقي | Logical Error |
| الخطأ التشغيلي | Runtime Error |
| الاستثناء | Exception |
| أخطاء المحاذاة | Indentation Error |
| أسلوب الكتابة | Code Style |
| خطأ الحافَّة | Off-by-one Error |
| المدقق | Debugger |
| التدقيق | Debugging |
| جمل التوكيد | Assert Statements |
| مراجعة الأقران | Peer Review |
| برمجيات التعاون | Collaboration Tools |
