
#### تمرين

- استخدم دالة `input()` لطلب `اسم المستخدم (username)` و `كلمة المرور (password)` من المستخدم وخزن كل منهما في متغير مناسب
- إذا كان اسم المستخدم هو `"admin"` وكلمة المرور هي `"abc123"`، اطبع: `"Welcome admin"`
- أو إذا كان اسم المستخدم هو `"backdoor"` وكلمة المرور هي `"let me in"`، اطبع: `"Nobody knows!"`
- خلاف ذلك، اطبع: `"Access denied!"`

```{python}
#| eval: false
password = 
```

#### تمرين

نريد تعيين درجة لطالب بناءً على نتيجته، وفقًا للجدول التالي:

| Mark | Grade |
|---|---|
| 90-100 | A |
| 80-89 | B |
| 70-79 | C |
| 60-69 | D |
| 0-59 | F |

ابحث عن الخطأ (أو الأخطاء) في الكود التالي وأصلحه. اختبره بدرجات (`score`) مختلفة للتأكد من صحته:

```{python}
#|eval: false
x =  100

if score >= 90:
  print("A")
if score >= 80:
  print("B")  
if score >= 70:
  print("C")
if score >= 60:
  print("D")
print("F")
```

تلميحات:

- قد تجد أنه من المفيد تعليق السطرين الأولين (بعلامة التعليق: `#`) وتعيين قيمة `score` مباشرة لاختبار الكود بسرعة.
- الكود يفتقد إلى عبارات `elif` و `else` (التكامل بين الجمل الشرطية)
- لا تحتاج إلى إزالة أي عبارة `print`.

#### تمرين

- اطلب من المستخدم إدخال عمره
- حوّل المدخل إلى عدد صحيح باستخدام دالة `int()`
- إذا كان العمر أقل من 5، اطبع: `"Child"`
- إذا كان العمر بين 5 و 12، اطبع: `"Kid"`
- إذا كان العمر بين 12 و 18، اطبع: `"Adolesence"`
- إذا كان العمر بين 18 و 65، اطبع: `"Adult"`
- خلاف ذلك، اطبع: `"Senior"`

ملاحظة: استخدام `elif` يعلق الشرط بانتفاء الذي قبله.

```{python}
# try it
```


#### تمرين

- اطلب `عرض (width)` و `ارتفاع (height)` المستطيل من المستخدم عن طريق دالة `input()`
- احسب مساحة المستطيل وخزنها في متغير `area`
- إذا كانت `area` أكبر من 100 و `width` أكبر من `height`، اطبع: `"المستطيل كبير وعريض"`
- إذا كانت `area` أكبر من 100 و `width` أقل من أو يساوي `height`، اطبع: `"المستطيل كبير وطويل"`

```{python}
# try it
```

#### تمرين

- اطلب من المستخدم إدخال رقم
- إذا كان الرقم الذي أدخله المستخدم أقل من 1، اطبع: `"الرقم يجب أن يكون أكبر من 1"` ثم اطلب من المستخدم إعادة الإدخال
- أخيرًا اطبع مجموع الأرقام من 1 إلى الرقم الذي أدخله المستخدم

```{python}
# try it
```
