---
title: الشرط
jupyter: python3
---

يسير تنفيذ الجمل البرمجية في اللغات الإجرائية -مثل بايثون- من الأعلى للأسفل. فإذا كتبنا الكود التالي:


```{python}
x = 1
x = 2
print(x)
```

فإن جملة التعيين التالية تكتُب قيمة `2` في نفس المحلّ الذي كتبت عليه جملة التعيين الأولى `1`. لذا ظهرت النتيجة: `2`.

كثيرًا ما نحتاج للتحكم فيما يُنفَّذ وما يُهمل أو ما يتكرر من الجمل البرمجية. فالحالات التي تستدعي تغيير ترتيب سير التنفيذ هي:

1. **التنفيذ المشروط**: تعليق تنفيذ قطعة كود على حصول حالة (أو أحوال) معيَّنة
2. **حلقة التكرار**: الرجوع لتنفيذ سطر سابق إلى حين حصول الغرض من هذه الحلقة
3. **التعامل مع الأخطاء**: حيث تتخذ بايثون نموذجًا في التنفيذ يجعل قطع كود مختلفة تنفَّذ بحسب نوع الخطأ

## الجملة الشرطية

الجملة الشرطية هي جملة مركَّبة من كلمة `if` وتعبير منطقي ثم الجمل التي يتعلق تنفيذها بناءً على هذا الشرط (وتكون داخل المحاذاة):

```{python}
if True:
    print('Inside')
print('Outside')
```

### تنبيه: المحاذاة العمودية

لاحظ أن **المحاذاة العمودية** (Indentation) (المسافات البيضاء أسفل كلمة `if`) في الكود أعلاه ليست لمجرد تسهيل قراءة الكود، بل هي التي تحدد التعليمات المشروطة. عادةً ما تكون المحاذاة عبارة عن 4 مسافات أو 2 أو أكثر، لكن لابد أن تكون موحَّدة طوال الكود.

لاحظ: بدون المحاذاة الصحيحة، سيظهر خطأ في الكود:

```{python}
#| error: true
#| 
if True:
print('Inside')
print('Outside')
```

إذا قمت بزيادة المحاذاة لكل من جملتي `print()`، فسوف يعمل الكود بتدفِّقٍ غيرِ الذي قصدناه ابتداءً. أي أنه سيطبع `Outside` عندما يكون في الواقع داخل اللَّبِنَة الشرطية.

```{python}
if True:
    print('Inside')
    print('Outside')
```

يؤدي الكود السابق إلى خطأ منطقي لن يظهر أبدًا كخطأ ولن يوقف البرنامج. لذا كن حذرًا مع المحاذاة في كتابة كود بايثون!

## التعبيرات المنطقية

أما الشروط فتستند إلى المنطق الرقمي الثنائي الذي نجد له في بايثون كلمتين من أصل اللغة هما:

1. كلمة `True` (وتساوي الرقم `1`) وتعبِّر عن تحقق الأمر
2. كلمة `False` (وتساوي الرقم `0`) وتعبِّر عن عدم التحقق الأمر

وكلاهُما يندرج تحت نوع خاصّ من صنف الأرقام وهو النوع **الثنائي** (`bool`).

أما الجملة الشرطية أو التعيين الشرطي ونحوه، فيتعلَّق بتحقق **عبارة منطقية**. فمن العبارات المنطقية: عبارة المقارنة:

| العلامة | الوصف |
| --- | --- |
| `a == b` | يساوي |
| `a != b` | لا يساوي |
| `a > b` | أكبر من |
| `a < b` | أصغر من |
| `a >= b` | أكبر من أو يساوي |
| `a <= b` | أصغر من أو يساوي |

هنا نستكشف عبارات تؤول إلى قيَم منطقية. العبارة الأولى: خمسة أكبر من تسعة؟

```{python}
b1 = 5 > 9
print(type(b1))
print(b1)
```

العبارة الثانية: هل طول كذا أكبر من طول كذا؟

```{python}
b2 = len('12345') > len('123456789')
print(b2)
```

### تركيب الشروط

يمكنك دمج شروط متعددة باستخدام عمليات الجمع والتخيير والحصر والعكس، لأنها تنتج قيمة منطقية. كما هو موضح في الجدول التالي:

| A | B | AND | OR  | XOR |
|----------|----------|----------|---------|------------------|
|     0    |     0    |    0     |    0    |        0        |
|     0    |     1    |    0     |    1    |        1        |
|     1    |     0    |    0     |    1    |        1        |
|     1    |     1    |    1     |    1    |        0        |

- **الجمع**: AND (**و**): تخرج 1 فقط إذا كان كلا المدخلين 1.
- **التخيير**: OR (**أو**): تخرج 1 إذا كان أحد المدخلين على الأقل 1.
- **الحصر**: XOR (**أو الحصرية**): تخرج 1 إذا كان المدخلان مختلفين.
- **العكس**: NOT (**ليس**): تخرج عكس المدخل (1 يصبح 0، و0 يصبح 1).

على سبيل المثال:

```{python}
age = 20
height = 175

if age > 18 and height > 170:
  print("You are eligible to donate blood")
```

يمكننا استخدام الأقواس لتجميع الشروط معًا. كما أنها تزيل أي غموض في ترتيب العمليات:

```{python}
age = 16
temperature = 15
is_wearing_coat = True

if age < 16 or (temperature < 20 and not is_wearing_coat):
  print("I suggest you don't go outside")
```

يُنظَر للشرط بأكمله كقيمة منطقية واحدة تكون `True` أو `False` ولا بأس بتجزئته حينما يسهل بذلك الفهم:

```{python}
is_minor = age < 16
is_cold = temperature < 20

if is_minor or (is_cold and not is_wearing_coat):
  print("I suggest you don't go outside")
```

### تسلسل المقارنات

تفهم بايثون المقارنات المتسلسلة. فعبارة `x < y <= z` تكافئ `x < y and y <= z`:

```{python}
low = 10
high = 20
x = 15

assert (low < x < high) == (low < x and x < high)
```

كذلك تراها تستعمل في المساواة:

```{python}
assert 3 == len('123') == len([10, 20, 30]) == len('abc')
```

### الجملة الشرطية المتكاملة

الصيغة المتكاملة للجملة الشرطية على النحو التالي:

```python
if <boolean expression>:
    <code>
elif <boolean expression>:
    <code>
else:
    <code>
```

- كلمة `if` (**إذا**) تبدأ الجملة المركبة الشرطية
- قد توجد [`else`](https://docs.python.org/3/reference/compound_stmts.html#else) (**وإلا**) مرة. وهي تعمل عند تخلُّف العبارة المنطقية السابقة لها سواءً كانت السابقة لها `if` أو `elif`.
- وقد توجد [`elif`](https://docs.python.org/3/reference/compound_stmts.html#elif) بينهما مرة أو أكثر (وهي اختصار لكلمة `else if` وتعني: **وإلا فإن**)، فتعمل مثل `else` معلَّقة بعبارة منطقية مثل `if`.

#### جرب

استكشف المنطق التالي بتغيير قيمة `x` كل مرة للتبع ما يحصل في كل مرة:

- `x = -5`
- `x = 0`
- `x = 1`
- `x = 5`

```{python}
x = -5

if x < 0:
    x = 0
    print('Negative changed to zero')
elif x == 0:
    print('Zero')
elif x == 1:
    print('Single')
else:
    print('More')

print("Always:", x)
```

وهذا تصوير لسير الأوامر لنفس الكود. ملاحظة: اضغط على الزر `Prev` أو `Next` للتنقل بين خطوات التنفيذ الفعلية:

<iframe width="800" height="500" frameborder="0" src="https://pythontutor.com/iframe-embed.html#code=x%20%3D%20-5%0A%0Aif%20x%20%3C%200%3A%0A%20%20%20%20x%20%3D%200%0A%20%20%20%20print%28'Negative%20changed%20to%20zero'%29%0Aelif%20x%20%3D%3D%200%3A%0A%20%20%20%20print%28'Zero'%29%0Aelif%20x%20%3D%3D%201%3A%0A%20%20%20%20print%28'Single'%29%0Aelse%3A%0A%20%20%20%20print%28'More'%29%0A%0Aprint%28%22Always%3A%22,%20x%29&codeDivHeight=400&codeDivWidth=350&cumulative=false&curInstr=5&heapPrimitives=nevernest&origin=opt-frontend.js&py=3&rawInputLstJSON=%5B%5D&textReferences=false"> </iframe>

لاحظ أن العبارة الأخيرة خارج كل اللَّبِنات الشرطية لذا يتم تنفيذها دائمًا.


## جملة التعيين المشروط

تستطيع في بايثون أن تجعل جملة التعيين تأخذ قيمتها بحسب شرطٍ معين. مثلاً:

```{python}
age = 18
status = 'adult' if age > 14 else 'child'

print(status)
```

وهي مكافئة للكود التالي:

```{python}
age = 18

if age > 14:
  status = 'adult'
else:
  status = 'child'

print(status)
```

ويمكن أن يتسلسل التعيين المشروط بالصيغة التالية:

```{python}
score = 75
grade = "A" if score >= 90 else "B" if score >= 80 else "C"
print(grade)
```


## تضمين الجمل الشرطية

جمل الشرط المضمنة هي جمل `if` داخل جمل `if` أخرى. على سبيل المثال:

```python
if <boolean expression>:
    if <boolean expression>:
        <code>
    else:
        <code>
else:
    <code>
```

ننبه مرة أخرى أن **المحاذاة مهمة**. يجب أن تكون جملة `if` الداخلية ذات محاذاة أكثر من جملة `if` الخارجية.

#### مثال

افترض أننا نريد تعيين درجة لطالب بناءً على نتيجته، وفقًا للجدول التالي:

| Mark | Grade |
|---|---|
| 95-100 | A+ |
| 90-94  | A  |
| 85-89  | B+ |
| 80-84  | B  |
| 70-79  | C  |
| 60-69 | D |
| 0-59 | F |

```{python}
score = 95

if score >= 90:
  if score >= 95:
    print("Outstanding: A+")
  else:
    print("Excellent: A")

elif score >= 80:
  if score >= 85:
    print("Very Good: B+") 
  else:
    print("Good: B")

elif score >= 70:
  print("Okay: C")

elif score >= 60:
  print("Poor: D")

else:
  print("Failed: F")
```

وهذا تصوير له:

<iframe width="800" height="500" frameborder="0" src="https://pythontutor.com/iframe-embed.html#code=score%20%3D%2095%0A%0Aif%20score%20%3E%3D%2090%3A%0A%20%20if%20score%20%3E%3D%2095%3A%0A%20%20%20%20print%28%22Outstanding%3A%20A%2B%22%29%0A%20%20else%3A%0A%20%20%20%20print%28%22Excellent%3A%20A%22%29%0A%0Aelif%20score%20%3E%3D%2080%3A%0A%20%20if%20score%20%3E%3D%2085%3A%0A%20%20%20%20print%28%22Very%20Good%3A%20B%2B%22%29%20%0A%20%20else%3A%0A%20%20%20%20print%28%22Good%3A%20B%22%29%0A%0Aelif%20score%20%3E%3D%2070%3A%0A%20%20print%28%22Okay%3A%20C%22%29%0A%0Aelif%20score%20%3E%3D%2060%3A%0A%20%20print%28%22Poor%3A%20D%22%29%0A%0Aelse%3A%0A%20%20print%28%22Failed%3A%20F%22%29&codeDivHeight=400&codeDivWidth=350&cumulative=false&curInstr=0&heapPrimitives=nevernest&origin=opt-frontend.js&py=3&rawInputLstJSON=%5B%5D&textReferences=false"> </iframe>

## خلاصة

تعلمنا في هذا الدرس كيفية تعليق نفيذ بعض أجزاء الكود على حسب شروط محددة، وهذا يكاد يكون نصف البرمجة في الواقع!

أما الدرس التالي فيتعلق [بالتكرار](04_iteration.qmd) المشروط والتكرار بمتوالية.