project:
  type: website
  preview:
    port: 4200
    browser: false
    navigate: false
  output-dir: _site

filters:
  - ./dir-ltr.lua

lightbox: auto

python: 
  path: .venv/bin/python

jupyter:
  kernelspec: 
    display_name: pythonia
    language: python
    name: pythonia

execute:
  # https://quarto.org/docs/computations/python.html#kernel-daemon
  daemon: true 

  # https://quarto.org/docs/computations/caching.html#jupyter-cache
  cache: true

  # https://quarto.org/docs/publishing/github-pages.html#freezing-computations
  freeze: auto

number-depth: 1

dir: rtl
website:
  # SEO Metadata
  title: "المقدمة البايثونية للبرمجة"
  description: "الأهداف: استيعاب ماهية البرمجة، ومعرفة إمكانياتها وحدودها. وإكساب مهارة التعبير الخوارزمي بلغة بايثون. وامتلاك القدرة على فتح مكتبات برمجية في بايثون سواء في الذكاء الاصطناعي أو تعلم الآلة أو بناء المواقع أو التصاميم ثلاثية الأبعاد."
  twitter-card: true
  open-graph: true

  # 
  favicon: favicon.png
  site-url: https://hassanalgoz.github.io/python/
  repo-url: https://github.com/hassanalgoz/python
  repo-actions: [issue]
  repo-subdir: book

  navbar:
    pinned: false

format:
  html:
    theme: [cosmo, custom.scss]
    mermaid:
      theme: neutral
    fontsize: 1.1em
    linestretch: 1.7
    grid:
      sidebar-width: 300px
      margin-width: 300px
    code-copy: true

lang: ar
language: _language_ar.yml


comments:
  utterances:
    repo: HassanAlgoz/python
    label: Comment
    issue-term: og:title