# بيئة الترميز

**النشاط: تعرف على بيئة التطوير (20 دقيقة)**

**الأهداف**:

- تعرف على كيفية عمل دفاتر الملاحظات التفاعلية مع Python
- تعرف على كيفية العمل مع Google Colab

**الأسئلة**

نظرة عامة على Colaboratory:

1. ما هو Colaboratory وكيف يفيد علماء البيانات؟

2. وصف الخطوات اللازمة لتحميل ملف من جهازك المحلي إلى Colaboratory.

3. كيف يمكنك تثبيت حزم Python في Colaboratory؟ قدم مثالاً.

4. اشرح كيفية تثبيت Google Drive في Colaboratory ولماذا قد يكون مفيدًا.

دليل Markdown:

5. ما هو Markdown ولماذا هو مفيد في دفاتر ملاحظات Colaboratory؟

6. قم بإدراج ثلاثة خيارات أساسية لتنسيق النص في Markdown وقدم مثالاً لكل منها.

7. كيف يمكنك إنشاء جدول باستخدام Markdown في دفتر ملاحظات Colaboratory؟ قدم جدولاً نموذجيًا.

8. اشرح كيفية إضافة صور إلى دفتر ملاحظات Colaboratory باستخدام Markdown.

**الموارد:**

- [نظرة عامة على Colaboratory](https://colab.research.google.com/notebooks/basic_features_overview.ipynb)
- [دليل Markdown](https://colab.research.google.com/notebooks/markdown_guide.ipynb)
- [النحو الأساسي لـ Markdown](https://www.markdownguide.org/basic-syntax/)