# قاموس المصطلحات

| English       | العربي         | ملاحظات                  |
|--------------------|---------------------|-----------------------|
| Variable           | متغير               |                       |
| Value           | قيمة               |                       |
| Expression           | تعبير               |                       |
| Statement           | عبارة               |                       |
| Clause           | جملة               |                       |
| Block           | لبنة               |                       |
| Snippet           | قصاصة               |                       |
| Code           | كود               |         معربة             |
| Function           | دالة                |                       |
| Method             | دالة مضافة          |       والكائن يكون مضافًا إليه               |
| Object             | كائن               |                       |
| Class            | صنف               |                       |
| Type           | نوع               |                       |
| Sequence           | تسلسل               |                       |
| String             | تسلسل حرفي          |                       |
| List               | تسلسل مرن           |                       |
| Dictionary         | قاموس               |                       |
| Set                | مجموعة              |                       |
| File               | ملف                |                       |
| Module             | وحدة               |                       |
| Package            | حزمة               |                       |
| Library            | مكتبة              |                       |
| Framework          | إطار عمل           |                       |
| Built-in           | مدمج               |                       |
| Tuple              | جَمْع          | فرد، زوج، جمع ثلاثي، جمع رباعي، ...إلخ                       |
| Set               | مجموعة              |                       |
| Parameter          | مُعامِل أو مُحَدِّد               |    وهي المتغيرات في التعريف                  |
| Argument           | وسيط               |          وهي القيَم المُمَرَّرَة             |


## Tuple

> Etymology. The term originated as an abstraction of the sequence: single, couple/double, triple, quadruple, quintuple, sextuple, septuple, octuple, ..., n‑tuple, ..., where the prefixes are taken from the Latin names of the numerals. The unique 0-tuple is called the null tuple or empty tuple. [Wikipedia](https://en.wikipedia.org/wiki/Tuple)

## Parameter

> A parameter (from Ancient Greek παρά (pará) 'beside, subsidiary' and μέτρον (métron) 'measure'), generally, is any characteristic that can help in defining or classifying a particular system (meaning an event, project, object, situation, etc.). [Wikipedia](https://en.wikipedia.org/wiki/Parameter)
