---
og:title: setup
---

# إعداد بيئة التطوير {.unnumbered}

تابع المقطعين التاليين حيث نشرح كيفية تنزيل وتثبيت مفسر لغة بايثون بالتفصيل:

<center>

<iframe width="560" height="315" src="https://www.youtube.com/embed/LlH91ACf7Wk?si=zMkPQEV0hE8F4V6m" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

</center>

ثم **بيئة التطوير** (Development Environment) وهي الأدوات البرمجية الأساسية والمساعدة في كتابة النص البرمجي وتنفيذه واختباره وتصحيحه وما إلى ذلك.

أما **محرر النص البرمجي** (Code Editor) فسنختار Visual Studio Code التابع لشركة مايكروسوفت، وهو مختلف عن Visual Studio.

- وهو مفتوح المصدر (أي: يمكن الاطلاع على نصه البرمجي). 
- ويستعمله 73.6% من 58,121 متجاوب في [استبيان StackOverFlow 2024](https://survey.stackoverflow.co/2024/technology#1-integrated-development-environment) وما يميزه أنه سهل بالنسبة للمبتدئ، وقوي بالنسبة للمتمكن.
- وتُعنى الشركة بدعمه وصيانته باستمرار وتطويره، كما يساهم فيه آخرون من خارج الشركة لكوْنه مفتوح المصدر.
- وتم تصميمه كي يقبل الزيادات واللواحق البرمجية ليختار كل مبرمج ما يناسبه من الأدوات حسب احتياجاته.

موقع المحرر: [https://code.visualstudio.com/](https://code.visualstudio.com/)

ولتشغيل القطع البرمجية راجع هذا الرابط: [https://code.visualstudio.com/docs/python/run](https://code.visualstudio.com/docs/python/run).

شاهد هذا المقطع لإتمام إعداد بيئة التطوير:

<center>
	
<iframe width="560" height="315" src="https://www.youtube.com/embed/MCYla_-tudw?si=j1RgW25zcRw1Cof6" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

</center>
