# تطبيقات معالجة النص الطبيعي

اصطلاحات: تسمى معالجة النص الحر الذي يكتبه البشر عادةً للتواصل بينهم: **معالجة اللغة الطبيعية**  (Natural Language Processing - NLP) وذلك للتفريق بينها وبين لغة البرمجة؛ إذْ هي لغة قصد بها التواصل مع الآلة لا مع البشر.

ومما يتعلق به من الموضوعات: **تحليل النصوص** (Text Analytics) وأحيانًا يسمى **التنقيب في النص** (Text Mining). ويتعلق به أيضًا مجال عُرف باسم **استرجاع المعلومات** (Information Retrieval) والذي تقوم عليه محركات البحث.

## التصنيف

- مثل: تصنيف الشكاوى حسب نوع المشكلة لتحسين سرعة الاستجابة.
- مثل: تصنيف البريد إلى عادي أو بريد غير مرغوب
- مثل: تحديد النغمة العاطفية (إيجابية، سلبية، محايدة) في التغريدات أو التعليقات؛ وذلك لتحليل تقييمات العملاء لفهم رضاهم عن منتج أو خدمة .. بشكل آلي.


## استخراج المعلومات

الهدف: استخراج معلومات محددة من النص. مثل: تحديد الأسماء والعلامات المهمة مثل الأشخاص، الأماكن، التواريخ، أو أسماء الشركات.

الكيفية: مطابقة أجزاء النص بأنماط لغوية ، أو باستعمال الإحصاء ، أو باستعمال الشبكات العصبية الاصطناعية العميقة ، أو جميع ما سبق.

- مثل: استخراج أسماء المدن وأرقام الهواتف من نصوص رسائل العملاء.
- مثل: استخراج أسماء المنتجات وأسعارها من الإعلانات وتحويلها إلى جداول

## البحث واسترجاع المعلومات

الهدف: البحث عن معلومات محددة من بين مجموعة كبيرة من النصوص.

- مثل: العثور على نصوص تتعلق بموضوع معين أو كلمات مفتاحية معيَّنة.

## تطبيقات أخرى

- **تصحيح الأخطاء اللغوية**: الإملاء والنحو والتصريف ومناسبة اللفظ للمعنى والخطأ الشائع.
- **التلخيص التلقائي**: إنتاج ملخص مختصر للمقالات الطويلة أو تقارير الأخبار.
- **إسناد القول إلى قائله**: مقارنة النصوص والتأكد من أصالتها ومعرفة مواضع الاقتباس وتخريج أقوالها.
- **إكمال النص**: المساعدة في كتابة الكود والرسائل والإعلانات التي تتسم بالنمطية. 
